### ISSUE TITLE
Issue when testing ProvisionUserToOperations

### ISSUE THREAD

**Issue by RobvanB** [microsoft/AppSource#3]
When I follow the article, and get to the point where I test the function ProvisionUserToOperations, I get the following error:
"System.TypeInitializationException: The type initializer for 'Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformPlugin' threw an exception. ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: Assembly required for the platform not found. Make sure assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.13.8.999, Culture=neutral, PublicKeyToken=31bf3856ad364e35' exists ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.13.8.999, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.\r\n   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)\r\n   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)\r\n   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)\r\n   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformPlugin.LoadPlatformSpecificAssembly()\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformPlugin.LoadPlatformSpecificAssembly()\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformPlugin.InitializeByAssemblyDynamicLinking()\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformPlugin..cctor()\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformPlugin.get_Logger()\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext..cctor()\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext..ctor(String authority)\r\n   at Submission#0.<ProvisionUserToAx>d__4.MoveNext() in D:\\home\\site\\wwwroot\\ProvisionUserToOperations\\run.csx:line 89\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Submission#0.<Run>d__3.MoveNext() in D:\\home\\site\\wwwroot\\ProvisionUserToOperations\\run.csx:line 44"
 Run

**Comment by amervitz** [comment]
I'm also having this issue, it seems the function app isn't restoring NuGet packages properly after the ARM template deployment. A workaround I've found is to restart the function app multiple times to trigger the package restore.

**Comment by hamptont** [comment]
amervitz is correct. This issue is caused by the Azure Function app not restoring the NuGet packages correctly, specifically the Microsoft.IdentityModel.Clients.ActiveDirectory.dll is not loaded

When we have seen this bug in the past it has been an issue with the Azure Function infrastructure itself. Here is one fix I was tracking (https://github.com/Azure/Azure-Functions/issues/590). Is this what you are running into? 

In the past a workaround for this issue has been to continue to try restoring the NuGet packages until it works. You can do this by restarting the Azure Function, or making the project.json file dirty (add a space to it then save) and try to run the function. The Azure Function will detect the change in the project.json file and trigger a reload of the NuGet packages. 

If you could paste the logs outputted by the Azure Function during the Nuget package reload that may help us identify the issue.

Another way to check if the NuGet packages loaded correct is to see if the project.lock.json file is created for your Azure Function. This file is created on NuGet package restore. If the restore failed, the file will not exist.

**Comment by hamptont** [comment]
If you want to open an issue on Azure Function team their github is at:
https://github.com/Azure/Azure-Functions

**Comment by hamptont** [comment]
Synced with RobvanB and we were able to get this working by deleting the DLLs from the nuget cache and they re-downloading them.

This is an issue with Azure Functions, not something we can fix from the Test Drive side. If you run into this issue in the future you can open an issue on https://github.com/Azure/Azure-Functions
